# .github/workflows/build.yml

name: Build Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: .\gradlew.bat clean build --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PotatoFPS
          path: build/libs/*.jar
